{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "cluster-autoscaler.labels" . | indent 4 }}
  name: {{ template "cluster-autoscaler.fullname" . }}
{{- end -}}
{{- if .Values.rbac.serviceAccountAnnotations }}
  annotations: {{ toYaml .Values.rbac.serviceAccountAnnotations | indent 4 }}
{{- end }}
  {{ if .Values.eks.enabled }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.eks.roleArn }}
    {{ end }}
