{{- if .Values.secretMapping.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "argo-tunnel.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "argo-tunnel.fullname" . }}
data:
  {{- if .Values.secretMapping.create }}
  secret-mapping.yaml: |
{{ toYaml .Values.secretMapping.content | trim | indent 4 }}
  {{- end }}
{{- end }}
