{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: argo-tunnel
  labels:
    ingress: argo-tunnel
  name: ssl
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.fqdn }}
    secretName: {{ .Values.ingrss.secret }}
  rules:
  - host: {{ .Values.ingress.fqdn }}
    http:
      paths:
      - backend:
          serviceName: ssl
          servicePort: http
{{- end}}
