apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeseal-webgui.fullname" . }}
  labels:
    {{- include "kubeseal-webgui.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ template "kubeseal-webgui.name" . }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "kubeseal-webgui.labels" . | nindent 8 }}
    spec:
      containers:
        - name: "api"
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ORIGIN_URL
              value: "{{ .Values.api.accessControlAllowOrigin }}"
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /secrets
              port: http
          readinessProbe:
            httpGet:
              path: /secrets
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: sealed-secret-configmap
              mountPath: /kubeseal-webgui/cert/kubeseal-cert.pem
              subPath: kubeseal-cert.pem
        - name: "ui"
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: sealed-secret-configmap
              mountPath: /usr/share/nginx/html/config.json
              subPath: config.json
      volumes:
        - name: sealed-secret-configmap
          configMap:
            name: {{ include "kubeseal-webgui.fullname" . }}
