{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: argo-tunnel
  labels:
    ingress: argo-tunnel
  name: blog
spec:
  tls:
  - hosts:
    - news.watercooler.wtf
    secretName: news
  rules:
  - host: news.watercooler.wtf
    http:
      paths:
      - backend:
          serviceName: blog
          servicePort: http
{{- end}}
