apiVersion: v1
kind: Service
metadata:
  name: {{ include "blog.fullname" . }}
  labels:
    {{- include "blog.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
    - port: {{ .Values.service.status_port }}
      targetPort: {{ .Values.service.status_port }}
      protocol: TCP
      name: http-status
  selector:
    {{- include "blog.selectorLabels" . | nindent 4 }}
