{{- if .Values.argo.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: argo-tunnel
  labels:
    ingress: argo-tunnel
  name: harbor
spec:
  tls:
  - hosts:
    - harbor.glen.dev
    secretName: glen.dev
  rules:
  - host: harbor.glen.dev
    http:
      paths:
      - backend:
          serviceName: harbor-harbor-portal
          servicePort: http
{{- end}}
